### PR TITLE
Fix crashes where `MessageList.searchView` is accessed before it was initialized

### PR DESCRIPTION
**Pull request by cketti**
Three different types of crashes related to this have been reported by Google Play.

See also: https://forum.k9mail.app/t/neue-version-offnet-nicht-mehr/5405

### CODE REVIEW

**Comment by shanuoon** [comment]
Unsuscribe.

**Comment by cketti** [comment]
@shanuoon: You'll have more luck clicking the "unsubscribe" link in the email you've received.

**Comment by Ahmedleo0** [comment]
Thanks very much

**Comment by Ahmedleo0** [comment]
Very good metold

**Pull request merged**
