### PR TITLE
Change theme colors

### PR DESCRIPTION
**Pull request by cketti**
Instead of blue, use gray as the primary color. Use that new primary color for the floating action button.
Slightly tweak the pink used as secondary color and use it in more places, e.g. selected messages.

|Light theme|Dark theme|
|-|-|
|image|image|
|image|image|

### CODE REVIEW

**Comment by Alecaddd** [comment]
adding @solangevalverde so she can review this as well

**Review by Alecaddd — APPROVED** [review]
This looks good. I can't speak for the code much but everything looks consistent with the K9-Mail brand.

**Comment by pwd-github** [comment]
Would it not be best to just implement dynamic colours from now rather than hard coding and having to do it once again later? 

https://m3.material.io/styles/color/overview

**Comment by Alecaddd** [comment]
@pwd-github thanks for the suggestion.

Unfortunately we're still currently on material design 2 and we're slowly moving towards unifying the UI to that toolkit to enforce consistency before defining an upgrade path to material 3.

We will definitely explore the possibility of implementing dynamic colors once possible.

**Pull request merged**
