### PR TITLE
Message View Redesign - Part 1: Change header

### PR DESCRIPTION
**Pull request by cketti**
Based on PR #6169. Updated the layout with the results from our latest design session.

This PR focuses on visual changes. As a result, some values are hard-coded. We'll add the code to properly populate the header view in separate pull requests.

### Before
image

### After
image image

The message view redesign issue: #6198

Things that are broken right now:
- message date is hard-coded
- recipient fields use hard-coded values ("to me +2")
- crypto status icon isn't properly aligned
- font size override from settings are ignored
- the contact picture is always displayed, even when disabled in settings
- the "reply all" button shows a snackbar
- the background when the overflow button is tapped isn't centered on the dots
- there are no tooltips displayed when long-pressing the "menu icons"

### CODE REVIEW

**Comment by ByteHamster** [comment]
The subject text looks kind of huge on my device. The header takes up more space than before, while displaying less information. Maybe it would be good to make the subject a little smaller.

Before/After:

**Comment by cketti** [comment]
I kind of like it as a default. Once we're satisfied with the layout, we can add back the font size overrides. That way you can use a smaller font size for the subject.

**Comment by xax** [comment]
The left side color bar, representing the account color, keeps the header together. That helps recognizing it intuitively.

The new design makes use of three (four with date/time?) different fond sizes instead of one in the old approach, Such a wild mix is typically not typographically appreciated at all.

**Comment by dal00** [comment]
I also think this is a step backwards. The reason to use K9 for me has been that it shows more info than other email clients. And easy access to headers. I wish I could select more header info to be show not less.

**Review by ByteHamster — APPROVED** [review]

**Comment by cketti** [comment]
@dal00: When tapping the gray area we plan to display a lot of details about the message. You can see a preliminary design in issue #6198. That would also be a good place to display user-selected headers, see #5742.

There's also the "Show headers" option that is not going away.

**Pull request merged**
