### PR TITLE
After sending, delete the draft message immediately, skipping the Trash folder

### LINKED ISSUE #2261: Remove drafts instead of moving them to the Trash on sending
### Expected behavior
Sending a message that was stored in the Drafts folder should remove the Draft

### Actual behavior
The draft is moved to the Trash folder.

### Developer notes

See #1467

### PR DESCRIPTION
**Pull request by schlagi123**
Add parameter in MessagingController delete message methods to force deletion of messages permanently. In case of sending a draft this permanent is set to true and fix #2261.

### CODE REVIEW

**Comment by schlagi123** [comment]
@cketti I am not sure, why a dependency could not resolved, but it is in a module, in that I have touching nothing.

**Comment by schlagi123** [comment]
One merge of the main branch and it worked.

**Review by cketti — CHANGES_REQUESTED** [review]
The build failed because Jitpack had a service outage last week.

Please don't change existing public `MessagingController` methods. Instead, add a new method `MessagingController.deleteDraftSkippingTrashFolder(Account, long)`. For private methods you can use the mechanism with the additional boolean parameter. But please rename the parameter to `skipTrashFolder`.

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :+1:

**Pull request merged**
