### PR TITLE
Prepare translation files for Weblate

### PR DESCRIPTION
**Pull request by wmontwe**
While looking into Weblate, I noticed that it got stuck on a merge conflict. This fix should enable Weblate to refresh and update its translations again.

The cause of the problem is the indentation used in the translations comming from Transifex. Unlike Weblate, which adheres to our code style, Transifex uses a two-space indentation, causing conflicts on each line.

I don't know if that behaviour of Transifex could be changed. In the worst-case scenario, we may need to manually format the pulled translations before incorporating them into the project.

### CODE REVIEW

**Comment by cketti** [comment]
We're currently not using Weblate. Changed strings files will get overwritten the next time I'll pull translations from Transifex.

Once we make the switch to Weblate it's probably easier to remove what's currently there, import from the repository again, and then pull the reformatted files from Weblate.

**Comment by wmontwe** [comment]
You're right that we currently are not using Weblate yet, so I've put it in locked mode to prevent external contributions.

I wanted to mention that Weblate is already configured to follow all translation changes in the repository seamlessly. This means that once we make the switch to Weblate, it should be relatively straightforward to just continue with it.

The only remaining issue is the indentation conflicts with translations coming from Transifex. A simple reformat fixes that, and we should be capable of managing future translations without hassle.

**Comment by wmontwe** [comment]
Rebased on latest changes

**Review by cketti — APPROVED** [review]
LGTM

**Pull request merged**
