### PR TITLE
Delete "Account list" and "Folder lists" in the font size settings

### LINKED ISSUE #6483: font size of the folder name, folder status fields don't changed
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.313-SNAPSHOT

### Where did you get the app from?

Other

### Android version

8.1

### Device model

emulator

### Steps to reproduce

1. Go to drawer menu
2. go to "Settings"
3. go to "General settings"
4. go to "Display"
5. in "Global" go to "Font Size"
6. in "Folder lists" click on "Folder name"
7. change checkbox item to "Tiniest"

### Expected behavior

It is expected that in the folder list in the drawer menu, or in the folder list in the "Manage folders", the font size of folders name will be changed.

### Actual behavior

There is no change in the font size

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mhf1998**
Fixes #6483

### CODE REVIEW

**Comment by cketti** [comment]
Instead of hiding the settings, can you please remove all code related to the account list and folder lists font settings?

**Comment by mhf1998** [comment]
yes. I will do it.

**Comment by rezazarchi** [comment]
> yes. I will do it. Should I remove related strings for them?

I guess If you want to remove all codes, you should also remove their related strings. However, they are a lot and may be used for other parts of the application.

**Comment by cketti** [comment]
> Should I remove related strings for them?

Apologies, I missed this question. Yes, please remove the strings, too. Of course only the ones that aren't used in other places.

**Comment by mhf1998** [comment]
It's okay.
yes. I will do it

**Comment by cketti** [comment]
Thanks :+1:

Merged as part of PR #6532

**Comment by mhf1998** [comment]
My pleasure.
Thank you. @cketti

**Pull request closed without merging**
