### PR TITLE
Add ability to switch between text/plain and text/html

### PR DESCRIPTION
**Pull request by tenzap**
This PR follows https://github.com/k9mail/k-9/pull/3936 which has not been updated for a while.

It:
- contains the same changes except I fixed it to work with current code
- adds a setting to choose the default content-type.

With them, the user can:
- set the default way to display messages (either plain text or HTML)
- on a "per demand" basis switch from one to another for the currently displayed message.

Related feature requests: https://github.com/k9mail/k-9/issues/906 https://github.com/k9mail/k-9/issues/1397

In case you or anyone is interested, the PR is also available for 5.8 in this branch https://github.com/tenzap/k-9/tree/f/5.8-MAINT/plain_text

Screenshot for the setting is below, other screenshots for per-message basis are in the original PR #3936
Screenshot_1631201917_256p

### CODE REVIEW

**Comment by dhebbeker** [comment]
Thank you @tenzap for pursuing the work. 

I stopped maintaining #3936. As I did not have any idea *when* to expect feedback from the maintainers or what to do, my motivation to keep updating that PR vanished. I guess it would have been nice if the work would have been coordinated. I blame myself for not getting directly in touch with the maintainers to get a perspective. Some of [those ways of communication](https://github.com/k9mail/k-9/blob/979a9b496854aa0bbba777cb33bb4d204c748d52/README.md#communication) already existed back then. And now there is also the "Discussions" feature in this GitHub project.

But this was long ago. I hope #1397 will be eventually fixed. :crossed_fingers:

**Comment by tenzap** [comment]
Hi @cketti , @ByteHamster , now that k-9 is part of the wider thunderbird community, is there a higher chance to see this long requested & awaited feature merged any time soon?

In the meantime I updated it to fit to your latest commits.

For those interested I also refreshed it for these branches 5.8, 6.0 & 6.2. It can be found here:

https://github.com/tenzap/k-9/tree/f/5.8-MAINT/plain_text
https://github.com/tenzap/k-9/tree/f/6.0-MAINT/plain_text
https://github.com/tenzap/k-9/tree/f/6.2-MAINT/plain_text

**Comment by tenzap** [comment]
Any explanation why this was closed would have been nice. Has this feature been implemented in the meantime?

**Comment by cketti** [comment]
I was closing all old pull requests that can't or won't be merged as-is. 

To do this feature properly, some UI/UX design work is required. Simply adding more entries to the menu is not acceptable. The cases where only a `text/plain` or a `text/html` part is present should be handled gracefully, etc.

I currently don't consider this feature important enough to warrant spending our time to do this properly. If you're volunteering to put in the necessary work, I can check if our designers are available for a meeting in January.

**Pull request closed without merging**
