### PR TITLE
Add markdown workflow to trigger a spotless check

### LINKED ISSUE #7216: Create workflow running `spotlessCheck` when only Markdown files change
Right now we [ignore changes to Markdown files](https://github.com/thundernest/k-9/blob/afb80619e5a663aa40e77616e157fc02ac84b917/.github/workflows/android.yml#L11) when running the Android workflow (that includes running `spotlessCheck`). However, `spotlessCheck` will also check Markdown files. 

So it's possible for a pull request to be merged that adds/changes a Markdown file violating some of our style rules (see #7215). And only the next pull request that triggers running the Android workflow will report a violation.

We should add a workflow that runs `spotlessCheck` when a Markdown file is changed and the Android workflow is not running anyway (e.g. because a code file was also changed).

### PR DESCRIPTION
**Pull request by wmontwe**
This fixes #7216

### CODE REVIEW

**Comment by cketti** [comment]
Can we prevent this workflow from running when a PR is also triggering the Android workflow (e.g. when a `.kt` file and an `.md` file was changed). Otherwise both workflows will check Markdown files.

**Comment by wmontwe** [comment]
Looking at the docs, it's not straight forward. There is an example to [including and exclude paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) but that will still trigger when there is a match on `**.md`. There is also a job [if condition](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif), but that goes beyond my knowledge. So maybe?

**Comment by wmontwe** [comment]
But the quality check could be a standalone workflow always checking everything and the android one just assembles and tests the app code base.

**Review by cketti — APPROVED** [review]
Potentially checking Markdown files twice is better than not checking them at all :+1:

**Pull request merged**
