### PR TITLE
Disable fling for message list swipe actions

### LINKED ISSUE #7015: swipe too quick to delete
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

pixel 7 pro

### Steps to reproduce

Turn on swipe function
Set delete swipe left or right
Go to email list
Swipe to delete
Email is deleted.

The issue is when you accidentally touch an email that shouldn't be deleted, the slitest swipe will delete the email.

The swipe is to sensitive and should have a delay or require longer swipe motion to activate the desired function especially for deleting an email.

Too many emails have been deleted accidnetly due to the existing implementation and over sensitivity of the gesture.

### Expected behavior

Longer swipe with decreased sensitivity.
More like apple mail swipe gesture.

### Actual behavior

A screen shot isn't needed please follow the steps laid out and test asndiscribed.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by fishchimp**
Passes `./gradlew spotlessCheck` and `./gradlew testDebugUnitTest`

Fixes #7015

### CODE REVIEW

**Review by cketti — CHANGES_REQUESTED** [review]
Thank you for looking into this issue :+1: 

The proposed change is messing with the swipe threshold. That's the minimum distance the view has to be dragged to trigger a swipe action. I don't think this is what's accidentally triggering swipe actions.

I'm fairly certain the real problem is the fling gesture. That's touching the screen, moving the finger in a certain direction, then lifting the finger off the screen. If the movement is fast enough, a fling gesture is detected. The problem is that there's no minimum distance the finger has to travel for a gesture to be considered a fling gesture (that's not entirely true, but for our purposes it's true enough). 

In most intentional fling gestures the finger travels a significant distance on the screen. Since our swipe threshold is fairly low, those fling gestures are also detected as (very fast) drag gestures. So I propose that we change `ItemTouchHelper` to allow disabling fling gestures completely.

Please add a new method `boolean isFlingEnabled()` to `ItemTouchHelper.Callback`. By default it should return `true`, so the original behavior of `ItemTouchHelper` is retained. Then in `ItemTouchHelper.checkHorizontalSwipe()` and `ItemTouchHelper.checkVerticalSwipe()` change

```java
if (mVelocityTracker != null && mActivePointerId > -1) {
```

to

```java
if (mCallback.isFlingEnabled() && mVelocityTracker != null && mActivePointerId > -1) {
```

In `MessageListSwipeCallback` override `isFlingEnabled()` and return `false` to disable fling gestures in the message list.

**Comment by fishchimp** [comment]
Hi @cketti ,

Thanks for quickly reviewing my PR, this is my first time contributing to an OSS, so I might have misunderstood how to implement it.

I have undone my previous commit and made the suitable changes you recommended to the `ItemTouchHelper.Callback `and override the new method `isFlingEnabled()` in `MessageListSwipeCallback` to disable the fling gesture in message lists.

Please do let me know if any more changes are required.

**Review by cketti — APPROVED** [review]

**Comment by cketti** [comment]
Thanks :+1:

> This is my first time contributing to an OSS, so I might have misunderstood how to implement it.

Don't worry. There was little information to go on. A big part of fixing bugs is identifying the exact problem and coming up with a patch that addresses it. Often there's more than one way to fix a bug. For complex issues it's often best to discuss an approach before implementing it. But if the change is rather small (like in this case), opening a pull request is a good way to get feedback on a specific approach. 

In this case it's not clear at all what the right fix is. I'm fairly sure a large part of accidental swipe actions are triggered by a fling gesture, but maybe that's only part of the problem. We'll put this in a beta version and find out.

Usually I don't give guidance as specific as in this a pull request. I could have told you that I wanted to try disabling fling gestures and then let you figure out how to accomplish that. However, I wanted this particular solution for a couple of reasons that would require more time to write down than I'd like to spend on this :smile:

**Comment by KomtGoed** [comment]
Thanks @fishchimp and @cketti! Is there a way we can test this? Or shall we wait for the next K9 release from the Google Store?

**Pull request merged**
